name: Build and deploy .NET Core app to Windows WebApp ChessChampion

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: ChessChampion
      AZURE_WEBAPP_PACKAGE_PATH: ChessChampionWebUI/publish
      DOTNET_CORE_VERSION: 9.0.x
      WORKING_DIRECTORY: ChessChampionWebUI
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout master
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Deploy Azure Infra
        run: >
          az deployment group create --resource-group ${{ secrets.AZURE_RG }} 
          --template-file Infrastructure/main.bicep 
          --parameters webSiteName=${{ env.AZURE_WEBAPP_NAME }}

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -o "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
